AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  Exclude:
    - examples/*.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
